# Base configs
baseurl: ""
image_fulls_loc: "/photography/images/fulls"
image_thumbs_loc: "/photography/images/thumbs"
google_analytics: ""

# UI configs
title: "Bergercookie's Thoughtstream"
subtitle: "See the world through my eyes!"
author: "Nikos Koukis"
header:
 title: "Φωτογραφια"
 subtitle: ""
footer:
 name: "Nikos Koukis"
 bio: "I am a Robotics/SLAM engineer, enthusiastic about new technologies, computers and programming. Photography is my latest hobby, I find it really awesome and I enjoy every minute I put in it. I'd love to hear what you think of the pictures in these pages so feel free to reach out to me if you have any feedback."
 github: "<a href=\"https://github.com/ramswaroop/photography\">Website template created by Ram Patra</a>"
social_urls:
  twitter: "https://www.twitter.com/bergercookie12"
  instagram: "https://www.instagram.com/bergercookie12"
  linkedin: "https://www.linkedin.com/in/nikos-koukis/"
  github: "https://www.github.com/bergercookie"
